# Generated by Django 2.2.5 on 2019-09-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150)),
                ('message', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='council_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=540)),
            ],
        ),
        migrations.CreateModel(
            name='issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField()),
                ('issue_depart', models.CharField(max_length=40)),
                ('issue_title', models.CharField(max_length=50)),
                ('issue_disc', models.TextField(max_length=300)),
                ('issue_status', models.CharField(max_length=20)),
                ('issue_remark', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=35)),
                ('username', models.CharField(max_length=24)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
