# Generated by Django 2.2.5 on 2019-09-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='issue_by',
            field=models.CharField(default='anonymous', max_length=25),
            preserve_default=False,
        ),
    ]
