# Generated by Django 2.2.5 on 2019-09-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_issues_issue_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='council_member',
            old_name='m_id',
            new_name='muser_id',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='issue_id',
        ),
    ]
