# Generated by Django 2.2.5 on 2019-09-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenance_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='maintenance_user',
        ),
    ]
