# Generated by Django 2.2.5 on 2019-09-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_delete_maintenance_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='council_member',
            old_name='m_id',
            new_name='muser_id',
        ),
    ]
