# Generated by Django 3.0.3 on 2020-03-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_auto_20190927_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='message',
            new_name='messages',
        ),
    ]
